### ISSUE TITLE
hey there

### ISSUE THREAD

**Issue by overloadchez** [NNNILabs/Multislope-3I#1]
hi nnni. this is overlord cheese, a kid you used to talk to on discoird. I got sent to a wilderness therapy and am now at a tbs. im still into electronics and am currently reading a book on circuit analysis (well, more like pushing my way through it, its suuuper boring)
miss ya. everything else was blocked and i dont have much time so yeah this was the on;ly place i could contact you

**Comment by NNNILabs** [comment]
Hi, glad to know you're doing okay! I've been wondering for a long time as well. 
I don't really like to read books about circuits because it's all so much maths. The Art of Electronics is the only thing I would consider a good read, and there's a PDF version available online. 
I hope everything works out fine and you will be active on Discord again.

**Comment by overloadchez2** [comment]
I'll take what I can get with circuits right now, plus I don't mind math (all I lack in terms of know how is calculus, and I'll be learning that soon). 
As for AOE, I've already asked my parents for it, and a PDF wouldn't work, cause, well... I don't really get to use screens. On that note, someday I will be on discord again but not anytime soon. Well, at least not consistently. it may be over a year before I can do that with the restrictions here.

...But I look forward to talking to you then
:)

**Comment by overloadchez2** [comment]
Also this may be the last time I'm trusted with electronics for a while so I apologize if, you know, I disappear.

**Comment by NNNILabs** [comment]
No problem, see you then! 
P.S. AoE 3 is like 50USD, you can probably get the second edition cheaper but wouldn't recommend it.
